import 'package:flutter/material.dart';

List<String> getShuffledPrompts() {
  final List<String> prompts = [
    "Loneliness",
    "Hate",
    "Righteousness",
    "Vexation of Spirit",
    "Psychological pain",
    "Contentment",
    "Emotional State",
    "Fear",
    "Compassion",
    "Anger",
    "Love",
    "Hope",
    "Faith",
    "Self Love",
    "Self Inquiry",
    "Zazen",
    "Guilt",
    "Right Understanding",
    "Right Thought",
    "Right Speech",
    "Right Action",
    "Right Livelihood",
    "Right Effort",
    "Right Mindfulness",
    "Right Concentration",
    "Suffering",
    "Fustration",
    "Letting Go",
    "Resentment",
    "Forgiveness",
    "Prayer",
    "Shame",
    "Humility",
    "Patience",
    "Humbleness",
    "Inner Voice",
    "Acceptance",
    "Reason",
    "Apathy",
    "Joy",
    "Peace",
    "Self Liberation",
    "Desire",
    "Courage",
    "Pride",
    "Empathy",
    "Spiritual Heart Posture",
    "Human Entropy",
    "Magnanimity",
    "Prudence",
    "Self Degradation",
    "Temperance",
    "Equanimity",
    "Vices",
    "Greed",
    "Untroubled",
    "Serenity",
    "Gratitude",
    "Gratefulness",
    "Self Indulgence",
  ];

  prompts.shuffle();

  debugPrint("length of prompts: ${prompts.length}");

  return prompts;
}
