List<String> getShuffledPrompts() {
  final List<String> prompts = [
    "Fear",
    "Compassion",
    "Anger",
    "Love",
    "Hope",
    "Faith",
    "Self Love",
    "Self Inquiry",
    "Zazen",
    "Guilt",
    "Right Understanding",
    "Right Thought",
    "Right Speech",
    "Right Action",
    "Right Livelihood",
    "Right Effort",
    "Right Mindfulness",
    "Right Concentration",
    "Suffering",
    "Fustration",
    "Letting Go",
    "Resentment",
    "Forgiveness",
    "Prayer",
    "Shame",
    "Humility",
    "Patience",
    "Humbleness",
    "Inner Voice",
    "Acceptance",
    "Reason",
    "Apathy",
    "Joy",
    "Peace",
    "Self Liberation",
    "Desire",
    "Courage",
    "Pride",
    "Empathy",
    "Spiritual Heart Posture",
    "Human Entropy",
    "Magnanimity",
    "Prudence",
    "Self Degradation",
    "Temperance",
    "Equanimity",
  ];

  prompts.shuffle();

  return prompts;
}
